# Generated by Django 3.2 on 2021-05-01 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azureaccesskey',
            old_name='account_name',
            new_name='name',
        ),
    ]
