# Generated by Django 3.2 on 2021-05-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_account_name_azureaccesskey_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('path', models.CharField(max_length=1000)),
            ],
        ),
    ]
