# Generated by Django 3.2 on 2021-05-09 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_downloadpath'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='downloadpath',
            name='name',
        ),
    ]
